name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v4
        with:
          packages: >-
            platform-tools
            platforms;android-37.0
            build-tools;37.0.0
            cmake;4.1.2
            ndk;29.0.14206865

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build debug and release
        run: |
          ./gradlew \
            :app:assembleLsposedDebug :app:assembleLspatchDebug \
            :app:assembleLsposedRelease :app:assembleLspatchRelease \
            :app:lintLsposedDebug :app:lintLspatchDebug --stacktrace --warning-mode all
